image: node:latest

cache:
  paths:
    - node_modules/
    - app/bower_components

deploy_production:
  stage: deploy
  environment: Production
  only:
    - master
  script:
    - yarn
    - yarn run build
    - firebase use --token $FIREBASE_DEPLOY_KEY default
    - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_DEPLOY_KEY
